language: go

go:
- "1.10"

go_import_path: github.com/TheThingsIndustries/mystique

cache:
  directories:
  - vendor

before_install:
- go get -u github.com/golang/dep/cmd/dep

install:
- dep ensure -v

script:
- make test
- make vet
- make fmt
