language: go

go:
- 1.9

go_import_path: github.com/TheThingsIndustries/mystique

cache:
  directories:
  - vendor

before_install:
- git config --global url."git@github.com:".insteadOf "https://github.com/"
- go get -u github.com/golang/dep/cmd/dep

install:
- dep ensure -v -vendor-only

script:
- make test
- make vet
- make fmt
