language: go

go:
- "1.11"

go_import_path: github.com/TheThingsIndustries/mystique

cache:
  directories:
  - $GOPATH/pkg/dep
  - vendor

install:
- make deps

script:
- make test
- make vet
- make fmt
