language: go

go:
- "1.12.x"

go_import_path: github.com/TheThingsIndustries/mystique

env:
  global:
  - GOPROXY=https://proxy.golang.org
  - GO111MODULE=on

install:
- make deps

script:
- make test
- make vet
- make fmt
