# [[constraint]]
#   branch = "ttn-master"
#   name = "github.com/TheThingsNetwork/ttn"
#   source = "https://github.com/TheThingsIndustries/ttn.git"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/client_golang"
